vulnerability_id: CVE-2019-12402
aliases: []
fixes:
- id: DEFAULT_BRANCH
  commits:
  - id: 4ad5d80a6272e007f64a6ac66829ca189a8093b9
    repository: https://github.com/apache/commons-compress
artifacts: []
notes:
- links:
  - https://commons.apache.org/proper/commons-compress/security-reports.html
  text: The file name encoding algorithm used internally in Apache Commons Compress 1.15 to 1.18 can get into an infinite loop when faced with specially crafted inputs. This can lead to a denial of service attack if an attacker can choose the file names inside of an archive created by Compress.
