vulnerability_id: CVE-2019-0224
aliases: []
fixes: []
artifacts: []
notes:
- links:
  - https://github.com/apache/jspwiki/commit/b17f699a4a099639beebb905cf4e04a8bea63b3c
  - https://issues.apache.org/jira/browse/JSPWIKI-1093
  - https://jspwiki-wiki.apache.org/Wiki.jsp?page=CVE-2019-0224
  text: In Apache JSPWiki 2.9.0 to 2.11.0.M2, a carefully crafted URL could execute javascript on another user's session. No information could be saved on the server or jspwiki database, nor would an attacker be able to execute js on someone else's browser; only on its own browser.
