vulnerability_id: CVE-2019-14379
aliases: []
fixes: []
artifacts: []
notes:
- links:
  - https://github.com/FasterXML/jackson-databind/commit/ad418eeb974e357f2797aef64aa0e3ffaaa6125b
  - https://github.com/FasterXML/jackson-databind/issues/2387
  - https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.7
  - https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8
  - https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9
  - https://github.wdf.sap.corp/Phosphor-Collaboration/core-io/issues/1
  - https://github.wdf.sap.corp/Phosphor-Collaboration/ehcache/issues/1
  text: SubTypeValidator.java in FasterXML jackson-databind before 2.9.9.2 mishandles default typing when ehcache is used (because of net.sf.ehcache.transaction.manager.DefaultTransactionManagerLookup), leading to remote code execution.
