vulnerability_id: CVE-2019-14439
aliases: []
fixes: []
artifacts: []
notes:
- links:
  - https://github.com/FasterXML/jackson-databind/commit/ad418eeb974e357f2797aef64aa0e3ffaaa6125b
  - https://github.com/FasterXML/jackson-databind/issues/2387
  - https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.7
  - https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8
  - https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9
  - https://github.wdf.sap.corp/Phosphor-Collaboration/core-io/issues/1
  - https://github.wdf.sap.corp/Phosphor-Collaboration/ehcache/issues/1
  text: A Polymorphic Typing issue was discovered in FasterXML jackson-databind 2.x before 2.9.9.2. This occurs when Default Typing is enabled (either globally or for a specific property) for an externally exposed JSON endpoint and the service has the logback jar in the classpath.
