vulnerability_id: CVE-2019-5729
aliases: []
fixes: []
artifacts: []
notes:
- links:
  - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5729
  - https://www.splunk.com/view/SP-CAAAQAD
  text: Splunk-SDK-Python before 1.6.6 does not properly verify untrusted TLS server certificates, which could result in man-in-the-middle attacks.
