vulnerability_id: CVE-2019-12410
aliases: []
fixes: []
artifacts: []
notes:
- links:
  - https://github.com/apache/arrow/commit/3bf4d80c8a295f144422077a09a6fc006ff43da5
  - https://github.com/apache/arrow/pull/5365
  - https://github.com/apache/arrow/pull/5392
  - https://lists.apache.org/thread.html/49f067b1c5fb7493d952580f0d2d032819ba351f7a78743c21126269@%3Cdev.arrow.apache.org%3E
  - https://www.openwall.com/lists/oss-security/2019/11/08/1
  text: While investigating UBSAN errors in https://github.com/apache/arrow/pull/5365 it was discovered Apache Arrow versions 0.12.0 to 0.14.1, left memory Array data uninitialized when reading RLE null data from parquet. This affected the C++, Python, Ruby and R implementations. The uninitialized memory could potentially be shared if are transmitted over the wire (for instance with Flight) or persisted in the streaming IPC and file formats.
