vulnerability_id: CVE-2019-7653
aliases: []
fixes: []
artifacts: []
notes:
- links:
  - https://nvd.nist.gov/vuln/detail/CVE-2019-7653
  - https://snyk.io/vuln/SNYK-PYTHON-RDFLIB-173988
  text: The Debian python-rdflib-tools 4.2.2-1 package for RDFLib 4.2.2 has CLI tools that can load Python modules from the current working directory, allowing code injection, because "python -m" looks in this directory, as demonstrated by rdf2dot. This issue is specific to use of the debian/scripts directory.
