vulnerability_id: CVE-2019-10086
aliases: []
fixes:
- id: DEFAULT_BRANCH
  commits:
  - id: 2412c90ba5584fed123fa6a33e752e6c8eaf74e9
    repository: https://github.com/apache/commons-beanutils
  - id: 4e410e068b8d367c53766a7da712b1b6f3fd8101
    repository: https://github.com/apache/commons-beanutils
  - id: 62e82ad92cf4818709d6044aaf257b73d42659a4
    repository: https://github.com/apache/commons-beanutils
artifacts: []
notes:
- links:
  - http://mail-archives.apache.org/mod_mbox/www-announce/201908.mbox/%3cC628798F-315D-4428-8CB1-4ED1ECC958E4@apache.org%3e
  - https://issues.apache.org/jira/browse/BEANUTILS-463
  - https://issues.apache.org/jira/browse/BEANUTILS-520
  text: In Apache Commons Beanutils 1.9.2, a special BeanIntrospector class was added which allows suppressing the ability for an attacker to access the classloader via the class property available on all Java objects. We, however were not using this by default characteristic of the PropertyUtilsBean.
