vulnerability_id: CVE-2019-0222
aliases: []
fixes: []
artifacts: []
notes:
- links:
  - http://activemq.apache.org/security-advisories.data/CVE-2019-0222-announcement.txt?version=2&modificationDate=1553686600404&api=v2
  - http://activemq.apache.org/security-advisories.html
  - https://github.com/apache/activemq/commit/98b9f2e2839da6ccff53260571b0e3a43aeb4285
  text: In Apache ActiveMQ 5.0.0 - 5.15.8, unmarshalling corrupt MQTT frame can lead to broker Out of Memory exception making it unresponsive.
